"""Generate complete, on-demand font shards; normal Hugo builds need no Python."""
from collections import Counter
from copy import deepcopy
from hashlib import sha256
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'static/fonts/LXGWBright-Regular.486e5fd6.woff2'
font = TTFont(source)
available = set(font.getBestCmap())
frequency = Counter()
for folder in ('content', 'layouts', 'data'):
    for path in (ROOT / folder).rglob('*'):
        if path.is_file() and path.suffix in ('.md', '.html', '.yaml'):
            frequency.update(map(ord, path.read_text()))
frequency.update(map(ord, (ROOT / 'hugo.yaml').read_text()))
common = sorted(available & frequency.keys(), key=lambda n: (-frequency[n], n))
remaining = sorted(available - set(common))
ui_text = (ROOT / 'themes/PaperMod/i18n/zh.yaml').read_text()
ui_text += (ROOT / 'assets/css/extended/custom.css').read_text() + '© · ← → » «\u00a0'
ui = sorted((set(map(ord, ui_text)) & available) - set(common))
groups = [common, ui]
groups += [remaining[i:i + 4096] for i in range(0, len(remaining), 4096)]
out = ROOT / 'static/fonts/subsets'
out.mkdir(exist_ok=True)
css = ['/* Generated by scripts/subset-font.py. Keep the original font and OFL license. */']
generated = set()
for points in groups:
    if not points:
        continue
    shard = deepcopy(font)
    options = subset.Options()
    options.flavor = 'woff2'
    worker = subset.Subsetter(options=options)
    worker.populate(unicodes=points)
    worker.subset(shard)
    temporary = out / 'generating.woff2'
    shard.save(temporary)
    digest = sha256(temporary.read_bytes()).hexdigest()[:12]
    filename = f'lxgw-{digest}.woff2'
    generated.add(filename)
    temporary.replace(out / filename)
    declared = set(points) if points == ui else set(points) - set(ui)
    ranges = ','.join(f'U+{point:X}' for point in sorted(declared))
    css.append('@font-face {\n font-family: lxgwbright;\n'
               f' src: url("../../fonts/subsets/{filename}") format("woff2");\n'
               ' font-style: normal;\n font-weight: 400;\n font-display: swap;\n'
               f' unicode-range: {ranges};\n}}')
(ROOT / 'assets/css/extended/font-subsets.css').write_text('\n'.join(css) + '\n')
for obsolete in out.glob('lxgw-*.woff2'):
    if obsolete.name not in generated:
        obsolete.unlink()
print(f'Generated {len(groups)} shards covering all {len(available)} code points.')
